### ISSUE TITLE
It's like a "dotfiles" repository

### ISSUE THREAD

**Issue by cecton** [earthquakesan/vimrc#1]
Hello,

Maybe you could make a dotfiles repository out of this. Many people use that principle: here an example of someone using stows https://github.com/kid/dotfiles (more at https://github.com/williamsmj/stowsh )

I'm personally more into a "home" directory base: https://github.com/cecton/cecile with a .gitgnore that excludes everything and a small script to initialize any home directory: https://gist.github.com/cecton/f8493716c31e95042417 

Best

**Comment by earthquakesan** [comment]
Hi @cecton! Thanks a lot for pointing out %) When I created this one, it was quite common to [name it like this](https://github.com/search?utf8=%E2%9C%93&q=.vimrc&type=). Will take a look at your approach, might work for me as well.

P.S. I am not currently using vim for development (switched to Atom). This repo is not really well-maintained.

**Comment by cecton** [comment]
Inactive, closing
